### ISSUE TITLE
🚧Test Issue

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/NukeLearning#3]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

This is a test issue

### Acceptance Criteria

- [ ] Complete using the test issue

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
@rishavnandi Hello!

Unfortunately no.  This project is not actually a real project.  I am in the middle of redoing my build system using [Nuke](https://nuke.build/) and this is just a test bed project to figure it all out and set it up before I migrate the build system for my real projects. 

But, I do have plenty of projects that you can help out on!!

**Refer to the projects below:** 
- [Velaptor](https://github.com/KinsonDigital/Velaptor)
- [CASL](https://github.com/KinsonDigital/CASL)
- [VersionMiner](https://github.com/KinsonDigital/VersionMiner)
- [BranchValidator](https://github.com/KinsonDigital/BranchValidator)
- [KDActionUtils](https://github.com/KinsonDigital/KDActionUtils)

I also have more projects coming over the next 6 or so months so keep an eye out.

You can also see any of the good first issues [here](https://github.com/orgs/KinsonDigital/projects/11/views/11?filterQuery=-status%3ADone+is%3Aissue+label%3A%22good+first+issue%22)

Right now there is only 2 issues still labeled as **good first issue**.  But I can definitely find more.
Also, if you want, come drop into my [Discord Server](https://discord.gg/qewu6fNgv7)!!  We can chat and you can ask questions as well.  😄
